### ISSUE TITLE
Resize based on only one dimensions, i.e. 300x, this means resize width to 300 and scale height as per aspect ratio

### ISSUE THREAD

**Issue by vikalpj** [PrimeDigitalGlobal/image-resize-lambda#2]

**Comment by vikalpj** [comment]
done in https://github.com/PrimeDigitalGlobal/image-resize-lambda/pull/9

With Smart crop size if height is not provided then make it makes it equal to width.

**Comment by rubish** [comment]
Not passing makes it equal to width or does it scales it keeping the aspect ratio without any restrictions on height?

**Comment by vikalpj** [comment]
@rubish It will scale up or down keeping the aspect ratio same. except for the smart crop feature, which always crops in square size when only width is given.
