### ISSUE TITLE
Add Following processing to work for images

### ISSUE THREAD

**Issue by vikalpj** [PrimeDigitalGlobal/image-resize-lambda#3]
- [x] **/image/WIDTHxHEIGHT:crop/key** - only crops by resizing the image and keeping portion as center gravity.
- [X] **/image/WIDTHxHEIGHT:cover/key** - resizes the image without cropping anything, one of the dimensions may be smaller than provided.
- [X] **/image/WIDTHxHEIGHT:smart/key** - do not crop more than necessary (user minimal option in smartcrop) and select area to keep based on interestingness.

**Comment by rubish** [comment]
In smartcrop, I think the minimal option is not required. I tested locally with two images and output seems good even without using it.

**Comment by vikalpj** [comment]
@rubish Sure, Let me check and update...

**Comment by vikalpj** [comment]
Added 3rd one is called smart crop with url 
/image/WIDTHxHEIGHT:smartcrop/key

**Comment by vikalpj** [comment]
PR - https://github.com/PrimeDigitalGlobal/image-resize-lambda/pull/7
